version: '3.5'

services:
    webserver:
        image: nginx:alpine
        volumes:
            - ./:/var/www/html
            - .docker/nginx/hosts/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            alert:
                ipv4_address: 192.168.100.4
        ports:
            - '80'

    app:
        build: .docker/app
        environment:
            PHP_IDE_CONFIG: serverName=192.168.100.4
            APP_ENV: dev
        volumes:
            - ./:/var/www/html
        networks:
            alert:
                ipv4_address: 192.168.100.2

networks:
    alert:
        name: alert
        driver: bridge
        ipam:
            config:
                -   subnet: 192.168.100.0/24
