parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\WebhookController:
        arguments:
            $logger: '@monolog.logger.webhook'

    App\Service\Bot\AlertBot:
        arguments:
            $token: '%env(resolve:ALERT_BOT_TOKEN)%'
            $recipient: '%env(resolve:CHANNEL_ID)%'

    App\Service\Bot\ContactBot:
        arguments:
            $token: '%env(resolve:CONTACT_BOT_TOKEN)%'
            $recipient: '%env(resolve:ADMIN_ID)%'

